export const SEARCH_CITIES_REQUEST = 'SEARCH_CITIES_REQUEST';
export const SEARCH_CITIES_FAILURE = 'SEARCH_CITIES_FAILURE';
export const SEARCH_CITIES_SUCCESS = 'SEARCH_CITIES_SUCCESS';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'; 


export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMSCAT_REQUEST = 'GET_ITEMSCAT_REQUEST';
export const GET_ITEMSCAT_FAILURE = 'GET_ITEMSCAT_FAILURE';
export const GET_ITEMSCAT_SUCCESS = 'GET_ITEMSCAT_SUCCESS';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_HIT_REQUEST = 'GET_HIT_REQUEST';
export const GET_HIT_FAILURE = 'GET_HIT_FAILURE';
export const GET_HIT_SUCCESS = 'GET_HIT_SUCCESS'; 
export const GET_ADDITEMS_REQUEST = 'GET_ADDITEMS_REQUEST';
export const GET_ADDITEMS_FAILURE = 'GET_ADDITEMS_FAILURE';
export const GET_ADDITEMS_SUCCESS = 'GET_ADDITEMS_SUCCESS'; 
 
export const GET_ORDERINFO_REQUEST = 'GET_ORDERINFO_REQUEST';
export const GET_ORDERINFO_FAILURE = 'GET_ORDERINFO_FAILURE';
export const GET_ORDERINFO_SUCCESS = 'GET_ORDERINFO_SUCCESS'; 
export const POST_CART_REQUEST = 'POST_CART_REQUEST';
export const POST_CART_FAILURE = 'POST_CART_FAILURE';
export const POST_CART_SUCCESS = 'POST_CART_SUCCESS'; 
export const GET_CARTDATA_REQUEST = 'GET_CARTDATA_REQUEST';
export const GET_CARTDATA_FAILURE = 'GET_CARTDATA_FAILURE';
export const GET_CARTDATA_SUCCESS = 'GET_CARTDATA_SUCCESS'; 


