export const SEARCH_CITIES_REQUEST = 'SEARCH_CITIES_REQUEST';
export const SEARCH_CITIES_FAILURE = 'SEARCH_CITIES_FAILURE';
export const SEARCH_CITIES_SUCCESS = 'SEARCH_CITIES_SUCCESS';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'; 
export const GET_TICKETSDATA_REQUEST = 'GET_TICKETSDATA_REQUEST';
export const GET_TICKETSDATA_FAILURE = 'GET_TICKETSDATA_FAILURE';
export const GET_TICKETSDATA_SUCCESS = 'GET_TICKETSDATA_SUCCESS'; 
export const GET_CITYID_REQUEST = 'GET_CITYID_REQUEST';
export const GET_CITYID_FAILURE = 'GET_CITYID_FAILURE';
export const GET_CITYID_SUCCESS = 'GET_CITYID_SUCCESS'; 



